CREATE TABLE UTILISATEUR
(
	IDUSER BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	DATE_CREATION TIMESTAMP,		
	TEL VARCHAR(20),
	MAIL VARCHAR(200),
	AD_VILLE VARCHAR(100),
	AD_CP VARCHAR(10),
	AD_RUE VARCHAR(100),
	NB_VOTES BIGINT,
	NOTE BIGINT,
	CONSTRAINT USER_PK PRIMARY KEY (IDUSER)
)
	
CREATE TABLE COMMENTAIRE
(
	IDCOMM BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	DATE_CREATION TIMESTAMP,
	IDUSER_CREATION BIGINT,
	IDCOMM_REF BIGINT,
	COMM VARCHAR(500),
	NB_VOTES BIGINT,
	NOTE BIGINT,
	COMM_VALIDATE BOOLEAN,
	CONSTRAINT COMM_PK PRIMARY KEY (ICOMM)
)