DROP TABLE KV01.UTILISATEUR;
DROP TABLE KV01.COMMENTAIRE;

CREATE TABLE KV01.UTILISATEUR
(
	IDUSER BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	DATE_CREATION TIMESTAMP,		
	PSEUDO VARCHAR(100),
	PASSWORD VARCHAR(100),
	TEL VARCHAR(20),
	MAIL VARCHAR(200),
	VILLE VARCHAR(100),
	CP VARCHAR(10),
	RUE VARCHAR(100),
	NB_VOTES BIGINT,
	NOTE BIGINT,
	ROLE BIGINT,
	CONSTRAINT USER_PK PRIMARY KEY (IDUSER)
) IN TBS_KV01_D INDEX IN TBS_KV01_X;

INSERT INTO KV01.UTILISATEUR(DATE_CREATION, PSEUDO, PASSWORD, ROLE, MAIL) VALUES(CURRENT DATE, 'Yann', 'pass', 0, 'yann.cahuzac@gmail.com');

CREATE TABLE KV01.COMMENTAIRE
(
	IDCOMM BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	DATE_CREATION TIMESTAMP,
	IDUSER_CREATION BIGINT,
	IDCOMM_REF BIGINT,
	THEME_ID SMALLINT,
	TITLE VARCHAR(100),
	COMM VARCHAR(500),
	NB_VOTES BIGINT,
	NOTE BIGINT,
	COMM_VALIDATE SMALLINT,
	CONSTRAINT COMM_PK PRIMARY KEY (IDCOMM)
) IN TBS_KV01_D INDEX IN TBS_KV01_X;

INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 1', 'Comm Test 1');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 2', 'Comm Test 2');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 3', 'Comm Test 3');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 4', 'Comm Test 4');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 5', 'Comm Test 5');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 6', 'Comm Test 6');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 7', 'Comm Test 7');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 8', 'Comm Test 8');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 9', 'Comm Test 9');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 10', 'Comm Test 10');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 11', 'Comm Test 11');
INSERT INTO KV01.COMMENTAIRE(DATE_CREATION, THEME_ID, TITLE, COMM) VALUES(CURRENT DATE, '1', 'Comm Title 12', 'Comm Test 12');